### ISSUE TITLE
Confirmation regarding yrInterp parameter

### ISSUE THREAD

**Issue by rossho32** [wfinsinger/tapas#2]
Could you please confirm if **yrInterp = NULL**  is equivalent to **yrInterp = 0** in CharAnalysis? 

Section 2.2 Parameter Selection

2.2.1 Pretreatment

**yrinterp** Years to interpolate record to. Charcoal counts, sample volume, and sample depths
are all interpolated before calculating charcoal accumulation rates. _Enter 0 here is you want to
interpolate to the median sample resolution (yr sample-1) of the selected record._

Higuera, P. (2009) CharAnalysis 0.9: Diagnostic and analytical tools for sediment-charcoal analysis. User's Guide, updated January 2009. 

Thank you for your insights!

**Comment by wfinsinger** [comment]
Hi rossho32,

Many thanks for your question regarding the equivalence between tapas and CharAnalysis.

I think you are right. When setting the argument yrInterp = NULL, the pretreatment_data() function will interpolate the record(s) to the median sample resolution. Thus, yrInterp = NULL should be equivalent to yrInterp = 0 in CharAnalysis.

See Lines 43-46 of the pretreatment_data() function:
## Calculate yrInterp ####
  if (is.null(yrInterp)) {
    yrInterp <- round(median(diff(ybp)))
  }

Very best,

Walter

**Comment by rossho32** [comment]
That's very helpful. Thank you so much for your response.
