### ISSUE TITLE
Error message in peak detection command

### ISSUE THREAD

**Issue by markconstantineiv** [wfinsinger/tapas#3]
Hi,

I'm having trouble getting the peak detection function to work. I  keep getting an error message that I haven't been able to figure out.  I've attached the message below and the data I'm trying to use.  Any help would be greatly appreciated. 

Cheers,

Mark

data 

cmTop | cmBot | AgeTop | AgeBot | charvol | char | chararea
-- | -- | -- | -- | -- | -- | --
0 | 0.5 | 2021 | 2019 | 0.115 | 345 | 31.7788462
0.5 | 1 | 2019 | 2018 | 0.253 | 1525 | 57.819431
1 | 1.5 | 2018 | 2016 | 0.178 | 147 | 40.0562852
1.5 | 2 | 2016 | 2015 | 0.366 | 618 | 98.0768329
2 | 2.5 | 2015 | 2015 | 0.154 | 1475 | 308.979571
2.5 | 3 | 2015 | 2015 | 0.317 | 1865 | 442.777971
3 | 3.5 | 2015 | 2007 | 0.483 | 970 | 249.457083
3.5 | 4 | 2007 | 1999 | 0.262 | 619 | 211.638133
4 | 4.5 | 1999 | 1991 | 0.149 | 758 | 180.78351
4.5 | 5 | 1991 | 1983 | 0.325 | 507 | 37.978172
5 | 5.5 | 1983 | 1975 | 0.287 | 275 | 24.0804663
5.5 | 6 | 1975 | 1967 | 0.183 | 822 | 98.8168647
6 | 6.5 | 1967 | 1959 | 0.252 | 294 | 51.0646869
6.5 | 7 | 1959 | 1951 | 0.217 | 321 | 2.2664685
7 | 7.5 | 1951 | 1943 | 0.157 | 413 | 26.1431116
7.5 | 8 | 1943 | 1935 | 0.26 | 115 | 8.57449858
8 | 8.5 | 1935 | 1927 | 0.313 | 293 | 21.9781205
8.5 | 9 | 1927 | 1919 | 0.279 | 229 | 151.011147
9 | 9.5 | 1919 | 1911 | 0.222 | 1279 | 155.350379
9.5 | 10 | 1911 | 1903 | 0.252 | 687 | 39.5456259
10 | 10.5 | 1903 | 1896 | 0.169 | 675 | 43.2481862
10.5 | 11 | 1896 | 1880 | 0.422 | 452 | 73.0699588
11 | 11.5 | 1880 | 1865 | 0.25 | 1336 | 72.3731696
11.5 | 12 | 1865 | 1850 | 0.317 | 482 | 107.344739

error message

> FCS_loc <- peak_detection(series = FCS_Mark, proxy = "chararea",
+                          first = -91, last = 110, yrInterp = 15,
+                          detr_type = "mov.median")
[1] "Warning: AgeTop = AgeBot for 2 samples, totaling 1cm"
[1] "The depth scale is continuous"
[1] "The age scale is continuous"
Error in seq.default(from = round(n.smooth), to = length(v), by = round(n.smooth/2)) : 
  wrong sign in 'by' argument

**Comment by wfinsinger** [comment]
Hi Mark,

Thanks for your message.
It seems that your time series is quite short (24 observations for c. 150 years), which poses some problems with the peak_detection() function. This function uses the 'smoothing_yr' argument to determine the smoothing-window width (in years) for: detrending the data, smoothing the signal-to-noise index (SNI), and setting the window width (in years) for the local thresholds. By default, the smoothing.yr argument is set to 500 years, thus substantially > than the duration of your time series. You wouldn't get the error message with shorter smoothing-window widths, though if the windows are too short you wouldn't have enough data points to constrain the gaussian mixture models...
I now added few lines to stop the code and return a 'Fatal error' in case the smoothing.yr value is too high with respect to the length of the time resampled series.
For instance, with 
mc2_loc_pd <- tapas::peak_detection(mc2, proxy = "chararea",
                                first = -71, last = 100,
                                yrInterp = 10,
                                smoothing_yr = 90,
                                detr_type = "mov.median",
                                thresh_type = "local", sens = FALSE),
the code works (PS: ages should be on the cal yr BP scale: e.g. df$AgeTop <- 1950 - df$AgeTop).

You may alternatively run the analysis using the pretreatment, detrending, and threshold functions to have a better control on what is going on in each of the analysis steps.

Let me know if this solved the issue, ok?

With very best wishes,

Walter
