### ISSUE TITLE
Error in 'check_pretreat()

### ISSUE THREAD

**Issue by MAdwoa** [wfinsinger/tapas#4]
When I run the 'check_pretreat()' function, I have this error message

Error in `cmB[slumps_index[i]]`:
! Can't subset columns past the end.
ℹ Location 6 doesn't exist.
ℹ There is only 1 column.
Run `rlang::last_trace()` to see where the error occurred.
> 

[MyDataRP.csv](https://github.com/wfinsinger/tapas/files/10976118/MyDataRP.csv)
Can you kindly advise?

**Comment by wfinsinger** [comment]
Hi MAdwoa,

That is odd. 
I downloaded your "MyDataRP.csv" file, ran the analysis (see code here below) and had no such error message.
You may try installing the most recent 'tapas' release (devtools::install_github("wfinsinger/tapas")). If that doesn't work, you may send me your R script and the data file by e-mail and I'll try to sort it out, ok?

Cheers, Walter


--- test R code ----------
library(devtools)
devtools::install_github("wfinsinger/tapas")
test_data2 <- read.csv("./data_in/MyDataRP.csv")

tapas::plot_raw(test_data2)
test_data2_check <- tapas::check_pretreat(test_data2)
tapas::plot_raw(test_data2_check)
test_data2_glob_pd <- tapas::peak_detection(test_data2,
                                            proxy = "chararea.mm2.",
                                            first = -71, last = 100,
                                            yrInterp = 15,
                                            smoothing_yr = 100,
                                            detr_type = "mov.median",
                                            thresh_type = "global")

**Comment by MAdwoa** [comment]
Hi Walter,

Thank you. I am checking that right away.

Regards,

Maame
________________________________
